name: Build and Deploy

on: [push,pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [0.0.4-dev2020.02.22]
    container:
      image: amutake/satysfi:${{ matrix.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          export HOME=/root
          eval $(opam env)
          opam update
          opam install satysfi-zrbase
          opam install satysfi-base
          opam install satysfi-make-html
          opam install satysfi-fonts-noto-emoji
          satyrographos install
          make build
